[package]
name = "edamame_backend"
version = "0.3.3"
edition = "2021"

[dependencies]
# Error
anyhow = "1.0.86"

# JSON
serde = { version = "1.0.204", features = ["derive"] }

# Hashing
blake3 = "1.5.1"
hmac = "0.12.1"
sha2 = "0.10.8"
hex = "0.4.3"
