# This workflow is responsible of:
#   - check if the code is correctly formatted
#   - check if there are no unhandled clippy warnings
#   - check if the code compiles
#   - run tests

name: Rust CI

on:
  push:
    branches:
      - "**"

env:
  CARGO_TERM_COLOR: always

# Cancel outdated workflows on the same branch to spare some CI time
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  fmt:
    name: Check code formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo fmt --check

  lint:
    needs: [fmt]
    name: Check unhandled clippy warnings
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo clippy -- -D warnings

  build:
    name: Build
    needs: [fmt]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        # --locked option to make build fail if Cargo.toml was updated but not Cargo.lock
      - run: cargo build --locked

  tests:
    name: Tests
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        # all unit tests in lib crates
      - run: cargo test
